/**
 * Common-misspelling fallback used when a full Hunspell dictionary is not installed.
 * Keys are lowercase misspellings; values are the corrected lowercase form.
 *
 * To enable full spell checking, drop `en_US.aff` and `en_US.dic` into the plugin folder
 * (`<vault>/.obsidian/plugins/note-capture/`); Note Capture will load them via nspell automatically
 * and this map becomes a supplement.
 */
export const COMMON_MISSPELLINGS: Record<string, string> = {
	teh: 'the',
	adn: 'and',
	hte: 'the',
	recieve: 'receive',
	recieved: 'received',
	seperate: 'separate',
	seperated: 'separated',
	definately: 'definitely',
	occured: 'occurred',
	occurence: 'occurrence',
	untill: 'until',
	wich: 'which',
	becuase: 'because',
	becasue: 'because',
	thier: 'their',
	alot: 'a lot',
	arguement: 'argument',
	auther: 'author',
	beleive: 'believe',
	acommodate: 'accommodate',
	accomodate: 'accommodate',
	arguements: 'arguments',
	enviroment: 'environment',
	goverment: 'government',
	independant: 'independent',
	neccessary: 'necessary',
	noticable: 'noticeable',
	occassion: 'occasion',
	persistant: 'persistent',
	publically: 'publicly',
	refered: 'referred',
	relevent: 'relevant',
	succesful: 'successful',
	succesfully: 'successfully',
	tommorow: 'tomorrow',
	truely: 'truly',
	wierd: 'weird',
	writen: 'written',
	basicly: 'basically',
	calender: 'calendar',
	concious: 'conscious',
	embarass: 'embarrass',
	existance: 'existence',
	fourty: 'forty',
	grammer: 'grammar',
	harrass: 'harass',
	liason: 'liaison',
	maintainance: 'maintenance',
	millenium: 'millennium',
	priviledge: 'privilege',
	questionaire: 'questionnaire',
	rythm: 'rhythm',
	supercede: 'supersede',
	threshhold: 'threshold',
};
